### ISSUE TITLE
TODO: Actions and formatting

### ISSUE THREAD

**Issue by SAtacker** [STEllAR-GROUP/hpx-rs#2]
Adding a few other things:

- [x] Github Actions CI for build check on MacOS
- [x] Github Actions CI for tests on MacOS
- [ ] Github Actions CI for build check on Linux
- [ ] Github Actions CI for tests on Linux
- [ ] Github Actions CI for build check on Windows
- [ ] Github Actions CI for tests on Windows
- [ ] Format for Rust code
- [ ] Format for Cpp Code
- [ ] Github actions CI status badge in readme

CC @pingu-73
